### PR TITLE
ECP-8: WordPress Plugin

### PR DESCRIPTION
**Pull request by Goose-Tech**
---
title: ECP-8, Create a WordPress Plugin for ethoFS
date: 2020-02-18T00:00:10.000Z # Change the date and time
description: >-
  Gather resources to develop a WordPress Plugin for ethoFS
---

ECP Originator: Goose-Tech  
ECP Sponsor: Goose-Tech  
ECP Motivation: Create a new WordPress plugin & widget for ethoFS  
ECP Summary: Update node network to support SSL/TLS, add encryption/password protection, update Ether-1 wallet and ethofs.com upload tools to allow for encryption/password protection of uploaded files, create WordPress plugin to allow secure backup of existing WordPress websites  
Discussion: 18 Feb. 2020 00:01 UTC to 23 Feb. 2020 00:01 UTC  
Voting: 14 Feb. 2020 00:01 UTC to 29 Feb. 2020 00:01 UTC  

Details:

This could be an EthoLabs initiative...

I propose we focus development on tools/apps that will make uploading to ethoFS more secure and user friendly. To that end, I would like to outline some of the steps needed to accomplish the goal of allowing any WordPress user to install the ethoFS plugin to allow for easy uploading of their website (as a backup) to the ethoFS network or widget to allow webhosts to offer secure (dropbox-style) file sharing via ethoFS. (Perhaps a Chrome or Firefox browser extension could be another avenue to pursue, but keeping with the webhosting foundation of ethoFS, we can begin with WordPress.) It will also be necessary for the plugin to allow for the purchase and storage of ETHO to faciliate its use. This could be accomplished with a smart contract linked to the user's registered ethoDNS.

Here are the steps I propose we take to achieve the goal of making ethoFS widely available to all WordPress users:

1. Secure the nodes with SSL/TLS
2. Update the protocol to allow for encryption & password protection of uploaded file(s)
3. Update the Ether-1 wallet and https://ethofs.com/uploads.html to allow for encryption/password protection of uploaded file(s)
4. Develop ethoDNS to allow users to register a .etho domain on the ETHO network
5. Develop WordPress plugin to allow for backup of existing website to ethoFS
6. Develop WordPress widget to allow sites to offer secure file sharing via ethoFS
Note: The WordPress plugin & widget will have to provide an easy way to purchase ETHO

How does it all work?

First, SSL/TLS is a requirement to ensure secure sending/receiving of sensitive data. Second, password protected files on the ethoFS network will ensure that private data cannot be accessed by anyone without the password (this includes node ops). After the wallets are updated, this added security and functionality will entice users to use the network for more than just static websites.

As for ethoDNS, the goal is ease of use. It is complicated what happens behind the scenes with ethoFS, but the average user does not need to be burdened with this. Our goal should be to make it as easy as possible to upload their website to ethoFS. This would look something like the following:

1. User purchases/registers ethoDNS domain (e.g. example.etho)
A smart contract is then tied to the ETHO address they used to pay for the domain. The same smart contract is used to fund uploads to the ethoFS network.
2. User points their .com or other domain to the .etho domain via MX or CNAME record
3. User uploads their website/content to their ethoDNS domain
Behind the scenes, the Ether-1 wallet or the WordPress plugin will automatically connect the upload hash to the user's ethoDNS domain. In the case of updating or adding new content to an existing site, the Ether-1 wallet or WordPress plugin will remove the previous upload hash, refund the balance, and reissue a new upload hash for the additional/updated content.
4. The network automatically propogates the ethoDNS domain with the new upload hash

### CODE REVIEW

**Comment by Goose-Tech** [comment]
Could this be any more complicated?

**Comment by fallengravity** [comment]
> Second, password protected files on the ethoFS network will ensure that private data cannot be accessed by anyone without the password (this includes node ops)

The user can upload encrypted files, encryption should be done locally anyway it is less risky if done locally than by us.

> Secure the nodes with SSL/TLS

What nodes? ethoFS? SN/MN/GN? There is no need for SN/MN/GN to use TLS, they do not have open RPCs by default. The nodes run of ETHs enode system - if you're speaking about ethoFS having TLS then please see: https://medium.com/@Ether1Official/ether-1-development-update-5-f53ab2f7c5d0 where we speak about the SSL cluster which is in development. 

 > Could this be any more complicated?
Yes, we probably could make it more complex

**Comment by Primate411** [comment]
This proposal looks like a road map.  There are many things here we can use here that will benefit us in the long run like ethoFS upload API, SSL cluster, server app to zip & encrypt content, ethoDNS.

To tackle something like this we need all the ether1 teams to split it up and work on their respective pieces.  etho.black would need to provide the ethoFS upload API & SSL cluster, another team would provide the ethoDNS and yet another would do the app that zips & encrypts content, first use case WordPress blog backups.

Whichever direction we decide to go in, I think Goose's topic sentence below needs more close examination

> I propose we focus development on tools/apps that will make uploading to ethoFS more secure and user friendly.

I agree with this sentiment and I would like to add we should make ethoFS more developer friendly. We can use adoption from end users and from developers alike.

I vote yes on the spirit of the ECP and the direction it suggests. Would like to see more concrete execution steps from all teams if we're able to get a quorum on this. Such an effort would require its own funding considerations as well.

**Comment by qbvbsite** [comment]
I see some good points in this ECP and as Primate mentioned will need to be split up into many different groups. 

I can see ETHOLabs help out with making ethoFS more user-friendly (using the new portal i'm going to propose), encryption of files to be uploaded (can be done via JavaScript so it's all client-side), and maybe the WP plugin (though this might be a little out of scope, I'm sure some code can be reused from the first 2 points though). 

Some questions I do have are:
Are you going to champion this and work on a plan of action?
What are your plans to fund each piece of the puzzle (council, community, etc)?

**Comment by Goose-Tech** [comment]
> The user can upload encrypted files, encryption should be done locally anyway it is less risky if done locally than by us.

Sure, encryption can be done with 7zip or other utility before uploading. What I am saying is that should be offered as a option at the time of upload. My goal here is to make uploading secure files easy for the non-tech user. This is a matter of whether or not it can pass the grandma test. :-)
 
> > Secure the nodes with SSL/TLS
> 
> What nodes? ethoFS? SN/MN/GN? There is no need for SN/MN/GN to use TLS, they do not have open RPCs by default. The nodes interact using ETHs enode system - if you're speaking about ethoFS having TLS then please see: https://medium.com/@Ether1Official/ether-1-development-update-5-f53ab2f7c5d0 where we speak about the SSL cluster which is in development.

To ensure a secure on-ramp and access to the data from behind corporate firewalls, I would prioritize this aspect of the development.

Also, all nodes should be required to have their own FQDNS so that they can be secured with SSL/TLS. This would be part of the completion of the SSL cluster. It would greatly increase the number of nodes within the cluster, which would further aid our goal of decentralizing everything.

**Comment by Goose-Tech** [comment]
> This proposal looks like a road map. There are many things here we can use here that will benefit us in the long run like ethoFS upload API, SSL cluster, server app to zip & encrypt content, ethoDNS.
> 
> To tackle something like this we need all the ether1 teams to split it up and work on their respective pieces. etho.black would need to provide the ethoFS upload API & SSL cluster, another team would provide the ethoDNS and yet another would do the app that zips & encrypts content, first use case WordPress blog backups.

Yes, this is a roadmap for the development of a product that we can use to help the average user take advantage of what the network has to offer. It is something that would roll out in phases:

Phase 1: SSL cluster
Phase 2: Update of wallet app to allow for password protected content to be uploaded to the network
Phase 3: Fiat gateway for ETHO w/APIs that can be used for WordPress plugin
Phase 4: WordPress plugin to allow for easy purchase of ETHO and one-click backup of entire website onto the ETHO network
Phase 5: WordPress widget to allow easy sharing of files through the ETHO network
 
> I vote yes on the spirit of the ECP and the direction it suggests. Would like to see more concrete execution steps from all teams if we're able to get a quorum on this. Such an effort would require its own funding considerations as well.

Thanks for the support. And yes, it would take several groups working together to build out the respective components.

**Comment by Goose-Tech** [comment]
> I see some good points in this ECP and as Primate mentioned will need to be split up into many different groups.
> 
> I can see ETHOLabs help out with making ethoFS more user-friendly (using the new portal i'm going to propose), encryption of files to be uploaded (can be done via JavaScript so it's all client-side), and maybe the WP plugin (though this might be a little out of scope, I'm sure some code can be reused from the first 2 points though).

If we can build out the first 2 phases of this proposal, it would position us better for the following phases. Basically, complete the SSL cluster, and secure all nodes. Then add client-side encryption to the existing wallet and web apps. Once that is complete, we do some marketing to show people how easy it is to share secure files using smart contracts. The fact that it's sealed by an SC means it could be used for legal purposes. This could open up a whole new realm of how legal documents are shared electronically (which is also where Ethereum is headed).

> Some questions I do have are:
> Are you going to champion this and work on a plan of action?
> What are your plans to fund each piece of the puzzle (council, community, etc)?

I am happy to spearhead this to delegate whatever work needs to be done for each aspect of the proposal. As for funding, I would hope that one or more aspects of this proposal could be funded by EthoLabs. Beyond that, I would also seek the support of the community via donations as well as from those community members who may choose to fund a particular aspect of the proposal (I myself would be willing to do that within reason).

**Comment by pistol22cal** [comment]
I am love this!!!! I just dont speak programming language !!!!!

**Comment by hashratez** [comment]
Goose and I've talked about the WordPress plugin honestly I need to do more research to be able to provide complementary suggestions

**Pull request merged**
