### PR TITLE
ECP-6: New EthoLabs Development Enclave 

### PR DESCRIPTION
**Pull request by qbvbsite**
**ECP Originator:** CableGod
**ECP Sponsor:** CableGod
**ECP Motivation:** Create a new development team to focus on dApp development and external services for Ether-1.
**ECP Summary:** Rework EthoLab's to help build a team of Ether-1 developers to work on dApps / services for Ether-1. 
**Discussion:** 13 Feb. 2020 00:01 UTC to 20 Feb. 2020 00:01 UTC
**Voting:** 13 Feb. 2020 00:01 UTC to 20 Feb. 2020 00:01 UTC

**Details:**

I propose we rework EthoLab's to help build a team of Ether-1 developers to work on dApps / services for Ether-1. The new EthoLabs would be comprised of a management team of 3 or 5 people that would manage the development team and prioritize what is being worked on. All dApps / services would be first approved by the Provisional Council then passed off to EthoLab's to manage. 

To help entice new developers as well as cover other costs EthoLabs would have a monthly budget of 25000 ETHO which will be managed by the EthoLab management to pay for developers, domains, hosting, etc. 

Action Items After Approved:
- Provisional Council creates new EthoLabs Management Team (Dissolve Old One)
- EthoLabs Management Setup new Multisig Wallet
- Move Old EthoLabs Funds to new Multisig
- Move First Monthly Payment to EthoLabs

### CODE REVIEW

**Comment by pistol22cal** [comment]
I agree with this

**Comment by qbvbsite** [comment]
> I agree with this -- POINT OF CONTENTION --- EthoLABS has 80k etho --- I move we hold funding for 90 days so they can spend what they already have - unless we want to consider this as an investment of ETHO to the future.

Think the current fund is 68K but I still think for the time being we fund it as an investment in future development. If at some point the fund gets too large we can halt it until it needs more funding. I see this as slow to start but can pick up very quickly and it would be nice to have a buffer for when development picks up.

**Comment by Bigpiggy01** [comment]
It would be nice with at least a list of priorities from labs so users can see what types of dapp development are being worked on. Funding dapp development without at least some slightly clearer goals is a bit nebulous.
If we can get that up, let's do it!

**Comment by qbvbsite** [comment]
> It would be nice with at least a list of priorities from labs so users can see what types of dapp development are being worked on/worked towards. Funding dapp development without at least some slightly clearer goals is a bit nebulous.
> If we can get that up, let's do it!

The first order of business would get a management team together and come up with a plan to acquire new talent as well as brainstorm ideas for projects that would be beneficial to the Ether-1 community. Personally I have a few ideas that I will be proposing to the council for approval. One of those ideas is a dApp portal that would act as a one-stop-shop for all Ether-1 dApps / services. The funding, for now, would sit unspent until management is in place and a development team put together. I think it's important to build up some buffer capital so when an opportunity presents itself we would not have to work about emergency funding.

**Comment by Primate411** [comment]
I think the ethoLABS team can get going without the need to inject more ETHO right away.  Building up some funds for when an opportunity presents itself is also something we should do as part of best practices.  In order to seize whatever opportunity it will seize, the LABS team will need to have some internal structure, some road map or list of goals/plans.

I'm with @Bigpiggy01 on this one, I'm all for it but it needs to be more fleshed out and have a more active posture.

For example I would love to see the vision of a dapp portal summarized with some achievable steps on a roadmap.  Something as simple as providing a basic dapp of any kind to benefit the community via the etholabs URL would go a long way to boost community morale and the desire to keep funding the LABS team.

**Comment by qbvbsite** [comment]
> ething as simple as providing a basic dapp of any kind to benefit the community via the etholabs URL would go a long way to boost community morale and the desire to keep funding the LABS team.

How ETHOLabs are pretty much outlined above, with the management team responsible for acquiring talent, manage approved projects, and handling paying out bounties/active developers. As for projects, I can't really speculate what would be brought forward with the exception of my portal idea. Once ETHOLabs is in place I'll be doing up and ECP for the portal proposal for sure in quick order. 

As for funding, IMO is crucial from the get-go to be able to budget what we can offer developers as well as how many developers we can float for projects. Without knowing this would make it difficult to budget development rates/bounties and other expenses once management is in place.

**Comment by Primate411** [comment]
What are some metrics the community can use 3, 6 and 12 months from now to gauge the progress of the ethoLABS team?

**Comment by qbvbsite** [comment]
> What are some metrics the community can use 3, 6 and 12 months from now to gauge the progress of the ethoLABS team?

The main metric would be the work done on approved projects with updates/demos/beta testing.. All the information about this would be available/posted on the website as well as in discord.

**Comment by Bigpiggy01** [comment]
We're not asking for set in stone metrics but something like:

A) Onestop dapp portal within roughly 6 months
B) First ______dapp active on ether1 by_____ /within________/around______
C) Gain participation from first new developer around__________.

It's early days and funding towards working towards something like this is in everyone's interest but at the same time we need to be accountable enough to give the community some goals vague though they may be to measure against.

I might fund porting a gambling dapp or two just because FREEDOM but that will be a bit further down the line.

**Comment by qbvbsite** [comment]
> We're not asking for set in stone metrics but something like:
> 
> A) Onestop dapp portal within roughly 6 months
> B) First ______ dapp active on ether1 by_____ /within________/around______
> C) Gain participation from first new developer around__________.
> 
> It's early days and funding towards working towards something like this is in everyone's interest but at the same time we need to be accountable enough to give the community some goals vague though they may be to measure against.
> 
> I might fund porting a gambling dapp or two just because FREEDOM but that will be a bit further down the line.

Hard to nail down the timeline without knowing how many developers are working on a given project and what the scope of it is. Those types of details will be in the dApp portal ECP when it is written up. 

With all projects going through the council for approval and 100% transparency on progress via the website should provide the accountability required. 

As far as how long before developers are actively working on projects, I would like to see the first project (dApp portal) ECP written within the first 2 weeks and having it being worked on the week it's approved.

**Comment by Primate411** [comment]
> As far as how long before developers are actively working on projects, I would like to see the first project (dApp portal) ECP written within the first 2 weeks and having it being worked on the week it's approved.

This satisfies my inquiry and I'm saying yes to the proposal in the condition that funds are transferred after a successful creation of the ethoLABS new management team and multisig wallet, tested and with ethoLABS' existing funds deposited.

**Comment by fallengravity** [comment]
In good conscience I cannot say this proposal as it stands is a good idea. ETHO Labs would be handing over 68K ETHO to the new enclave. 68K is technically 2 and a half months worth of funding according to the budget, I think that the council should allow for creation and the take over of labs but evaluate the proposed budget of 25K in 2 months once their initial funding from ETHOLabs starts to run out, otherwise, we're just giving the new enclave 93K ETHO with no proven development and no guarantee on the project's money. If we're already funding them by dissolving ETHOLabs there is **No reason** to consider funding them with the developer fund until we either see some progress/development.

**Comment by qbvbsite** [comment]
I have already addressed this in the comments above. Payments would not start until the management team is in place and the first project is approved by council. 

This ECP is to secure funding so that the management team can budget for developers / projects once in place and make sure it can continue to operate going forward. Budgeting is very important and the management team can’t do this without unless knowing how much is coming in. Also, as stated above funding can be changed by council via an ECP.

**Comment by fallengravity** [comment]
I think a guarantee of a review of your budget ECP before ETHOLabs fund runs out is better than handing 93K ETHO to a development team with no proven history.

**Comment by qbvbsite** [comment]
Council isn’t handing any additional funds until things are in place and ETHOLabs has a project to work on. As stated it’s important to secure funding so we know it can continue to operate once we have a team together and working on projects.

**Comment by dylie** [comment]
I must agree with Fallen in this case...

**Pull request merged**
