### PR TITLE
ECP-9: Team PistolCrypt Creation

### PR DESCRIPTION
**Pull request by Primate411**
**ECP Originator:** `@Pistol of $ETHO (ID: 378374529707278347)`
**ECP Sponsor:** `@Primate of $ETHO (ID: 393479955956367370)`
**ECP Motivation:** Create team responsible for social media engagement and management  
**ECP Summary:** Setup PistolCrypt team responsible for Discord and other Social Media Management, Community Management and Marketing.
**Discussion:** 25 Feb. 2020 00:01 UTC to 3 Mar. 2020 00:01 UTC  
**Voting:** 3 Mar. 2020 00:01 UTC to 10 Mar. 2020 00:01 UTC  

## Details:
PistolCrypt members are as follows:

Member Name | Member Role | Member Payment
--- | --- | ---
Pistol | Team Leader | 900
Theekgb | Mod / Community Developer | 400
OzzyBoganTech | Mod | 100
Alob | Mod / Ambassador | 300
Goose | YouTube  | 600
Hashington | Mod / Ambassador | 300
Crypto_Saiyan | Community Manager | 800
Exlo | Community Developer | 300
Primate | Documentation Manager | 300
YaYa | Social Media Manager | 800

## Roles and Hierarchy
* Council is first
* Team Leader - Not all powerful - Must have council approval to hire and fire - simple in chat vote is all that is needed. Team Leader is fully responsible for role assignments for each team member and is free to move members around as needed. Assigns team members, pay, and reports directly to the council – Major changes to discord shall be voted on within the council no ECP needed – This role has equal power as the discord server admin.
* Community Manager – These are senior moderators able to make vast and sweeping changes to discord, must be approved by the Team Leader.
* Community Developers – Members with this role develop for Ether-1 community and can be core developers as well.
* Social media managers - In charge of representing a company across social channels as the sole voice of the brand. They respond to comments, compile campaigns and create content. These experts provide organizations with the guidance needed to enhance their online presence.
* Management Roles - These roles have specific skill sets needed in the areas assigned.
* Moderator - Moderators can do basic things like edit/delete messages, ban/kick people who violate any rules put in place, and make sure the Discord is a safe, healthy environment to do whatever is happening in the server.

## Social Media
* Discord
   * Community Manager
   * Moderator
   * Ambassador
   * Community Developer
* Social Media Managers
   * Twitter/FB/Insta/Telegram/Telegram ANN- Content Sponsor
   * Medium/Reddit/BCT Forum- Content Sponsor
   * Github- Content Sponsor
   * YouTube- Content Sponsor
   * Websites- Content Sponsor
   * Documentation- Content Sponsor

## Marketing
This team does not solely produce marketing on its own, marketing should be a separate team all together. However, for content such as Tweet’s, posts, and articles should be at the discretion of the Team and its Leadership. As well as any maintenance needed should not need council approval or any approval – If you know something is broken and you can fix it, then you should.

## Old Social Media Positions
* Twitter  >  Primate
* Facebook  >  YaYa
* Instagram  > YaYa
* Medium  >  Primate
* Podcast  >  Goose | YaYa (Anchor.fm)
* YouTube  >  Fallen | Cap
* Reddit > Fallen | Pistol | Primate
* Blockfolio > James | Fallen | Primate

## New Social Media Positions
* Discord Moderators | - Alob - Theekbb - Hashington - Ozzy
* Community Managers | - Discord Sr. Mods - Crypto_Saiyan - Core Team retains admin powers to discord
* Ambassadors | - Alob - Hashington
* Twitter | - Primate - Pistol - YaYa
* Facebook | - YaYa - Primate
* Insta | - YaYa - Primate
* Medium | - YaYa - Primate
* Podcast | - Goose - YaYa
* Youtube | - Fallen - Goose
* Reddit  | - Fallen - Pistol - Primate - Goose
* Blockfolio | - James - Fallen - Primate
* Websites | - Fallen and whomever fallen decides to work with as I feel this is more of a core dev decision.

Any new accounts will be approved by Social Media Managers and they will have access to all social media accounts. Social Media Managers also have the responsibility of adding moderators such as for Reddit or BCT Forum. As well as any forums we may have that deal with Ether-1. These moderators will be volunteer only and not considered staff or team members. Further, Council and Core Dev's still determine who has access to what accounts other than Social Media Managers at the discretion of those accounts Administrators. This does not change in my vision until the Permanent Council is elected. Or, if an ECP is passed in the future.

Further- I would request your active participation within the community. If you can not or are unwilling to be active in Ether-1 please do not waste my time by being a part of this team or its funds.

Finally, members who do not receive payment from this team are sponsored by another team and have chosen to be a part of this team. Example, Fallen as he is a member of etho.black team.

## Budget
Budget Approx - 6000 ETHO - Team Leader is responsible for properly paying all members of the team.

* Team Leader - 900 ETHO - Per Month
* Community Manager - 800 ETHO - Per Month
* Social Media Manager - 800 ETHO - Per Month
* Community Developer - 300 ETHO - Per Month - Plus Bounties
* Content Sponsor - 300 ETHO - Per Month
* Ambassadors - 200 ETHO - Per Month
* Mods - 100 ETHO - Per Month

_Excess budget shall be used for bounties within social media or discord and used at the discretion of Social Media and Community Manager's with the approval of the team leader._

### CODE REVIEW

**Comment by Primate411** [comment]
Can you put more info about the roles & responsibilities of the Team Leader and Community Manager?

Will the PistolCrypt team work on actively promoting #DecentralizeEverything ideology and direct people into the ether1.cloud, etho.black, ETHOLabs, and other trusted Ether-1 enclaves as needed?

Will the PistrolCrypt team do everything in their power to be impartial and level headed moderators of the primary Ether-1 Discord? This includes mentoring trolls within reason and always de-escalating situations in the interests of productive work within Ether-1?

**Comment by pistol22cal** [comment]
> Can you put more info about the roles & responsibilities of the Team Leader and Community Manager?
> 
> Will the PistolCrypt team work on actively promoting #DecentralizeEverything ideology and direct people into the ether1.cloud, etho.black, ETHOLabs, and other trusted Ether-1 enclaves as needed?
> 
> Will the PistrolCrypt team do everything in their power to be impartial and level headed moderators of the primary Ether-1 Discord? This includes mentoring trolls within reason and always de-escalating situations in the interests of productive work within Ether-1?

Team Leader – Leader of the Team - responsible for developing and implementing a timeline their team will use to reach various goals. Some of the ways team leaders ensure they reach their goals is by delegating tasks to their members, including themselves.
Community Manager – The liaison between the community, dev-team, and council. – The Community Manager is also a Senior Moderator for Discord. Community Manager is a discord role only and all discord roles fall under the community manager except those that hold Admin or equivalent.
This team is not intended to be a source of content development and function in a management and execution type of role. While the team can and will Tweet, Reddit post, and supply content. This is ultimately the work of a marketing team in my opinion. The team will work close to all other teams to insure all information is presented properly in all the various Social media’s as needed and where appropriate. 
Moderators and Sr. Moderators should not need hand holding in the performance of their duties. The rules of conduct are clear, if a moderator feels a violation calls for kick or ban or warning it is up to that individual Moderator. However, this is subject to change if needed and is at the sole discretion of the Community Manager and Team Leader. If the community or council feels power being abused. A 6/7 vote of the council can remove any member of the team without question including the team leader.

**Comment by pistol22cal** [comment]
> Can you put more info about the roles & responsibilities of the Team Leader and Community Manager?
> 
> Will the PistolCrypt team work on actively promoting #DecentralizeEverything ideology and direct people into the ether1.cloud, etho.black, ETHOLabs, and other trusted Ether-1 enclaves as needed?
> 
> Will the PistrolCrypt team do everything in their power to be impartial and level headed moderators of the primary Ether-1 Discord? This includes mentoring trolls within reason and always de-escalating situations in the interests of productive work within Ether-1?

Team Leader – Leader of the Team - responsible for developing and implementing a timeline their team will use to reach various goals. Some of the ways team leaders ensure they reach their goals is by delegating tasks to their members, including themselves.
Community Manager – The liaison between the community, dev-team, and council. – The Community Manager is also a Senior Moderator for Discord. Community Manager is a discord role only and all discord roles fall under the community manager except those that hold Admin or equivalent.
This team is not intended to be a source of content development and function in a management and execution type of role. While the team can and will Tweet, Reddit post, and supply content. This is ultimately the work of a marketing team in my opinion. The team will work close to all other teams to insure all information is presented properly in all the various Social media’s as needed and where appropriate. 
Moderators and Sr. Moderators should not need hand holding in the performance of their duties. The rules of conduct are clear, if a moderator feels a violation calls for kick or ban or warning it is up to that individual Moderator. However, this is subject to change if needed and is at the sole discretion of the Community Manager and Team Leader. If the community or council feels power being abused. A 6/7 vote of the council can remove any member of the team without question including the team leader.

**Comment by Primate411** [comment]
Will the PistolCrypt team work on actively promoting #DecentralizeEverything ideology and direct people into the ether1.cloud, etho.black, ETHOLabs, and other trusted Ether-1 enclaves as needed?

By this I mean will the team make users aware of the internal structure of the Ether-1 Ecosystem and point people in the right direction if for example they have dApp portal issue, forward them to ETHOLabs and @qbvbsite ?

**Comment by Primate411** [comment]
If together as an ecosystem we find more decentralized ways to do social media coverage, will the PistolCrypt team be willing to share some of its social media account control? Will this require a 4/7 vote or a 6/7 vote?

**Comment by pistol22cal** [comment]
> Will the PistolCrypt team work on actively promoting #DecentralizeEverything ideology and direct people into the ether1.cloud, etho.black, ETHOLabs, and other trusted Ether-1 enclaves as needed?
> 
> By this I mean will the team make users aware of the internal structure of the Ether-1 Ecosystem and point people in the right direction if for example they have dApp portal issue, forward them to ETHOLabs and @qbvbsite ?

I dont see why we would not promote other enclaves / pools / pages / discords / Anything Ether-1 of valuable to Ether-1 should be promoted.

**Comment by Primate411** [comment]
> > Will the PistolCrypt team work on actively promoting #DecentralizeEverything ideology and direct people into the ether1.cloud, etho.black, ETHOLabs, and other trusted Ether-1 enclaves as needed?
> > By this I mean will the team make users aware of the internal structure of the Ether-1 Ecosystem and point people in the right direction if for example they have dApp portal issue, forward them to ETHOLabs and @qbvbsite ?
> 
> I dont see why we would not promote other enclaves / pools / pages / discords / Anything Ether-1 of valuable to Ether-1 should be promoted.

I also don't see why not but I'm just putting a placeholder in this ECP debate to put it on the record for future reference if ever necessary.

**Comment by qbvbsite** [comment]
I'm good with this.

**Comment by Crypto-Saiyan** [comment]
Sounds great.

**Comment by Primate411** [comment]
Proposal has passed with 5-1 approval:
Yes: @qbvbsite @pistol22cal @Crypto-Saiyan @hashratez @Primate411 
No: @dylie 

Next funding date is April 1st.  Team PistolCrypt a.k.a etho.pink has been funded for the first month from some old bounty funds.

**Comment by Primate411** [comment]
Note: @bigpiggy01 has abstained from the vote.

**Pull request merged**
