### PR TITLE
ECP-4 Salary for ETHO Black Wallet - Dev Payments

### PR DESCRIPTION
**Pull request by pistol22cal**
ECP Originator: Pistol22cal
ECP Sponsor: Pistol22cal
ECP Motivation: Pay the DEV Team
ECP Summary: Pay DEV Team

Discussion: 06 Feb. 2020 00:01 UTC to 13 Feb. 2020 00:01 UTC
Voting:  14 Feb. 2020 00:01 UTC to 21 Feb. 2020 00:01 UTC

Details:

Pay DEV Team 50000 ETHO per month - Reevaluate every 90 days for price adjustments - Internal votes only every 90 days no need to create a new ECP - This amount goes to the etho.black wallet. This funding is to be used to pay Developers.

### CODE REVIEW

**Comment by Primate411** [comment]
I like the new way of using ECP's. This one needs the discussion and voting information input according to our customary ways.

I agree with paying 20K ETHO per month for Fallen to work on improving the Ether-1 ecosystem.

**Comment by pistol22cal** [comment]
> I like the new way of using ECP's. This one needs the discussion and voting information input according to our customary ways.
> 
> I agree with paying 20K ETHO per month for Fallen to work on improving the Ether-1 ecosystem.

i was not sure how to do that........ lol - ill fix it now

**Comment by Bigpiggy01** [comment]
Looks good to me.

**Comment by dylie** [comment]
I think it would be better if we funded the "etho.black" as the development team. This way only 1 payment has to be made to their wallet and etho.black devs can use it how they want.

**Comment by pistol22cal** [comment]
> I think it would be better if we funded "etho.black" as the development team. This way only 1 payment has to be made to their wallet and etho.black devs can use it how they want.

Ive made some changes to the ECP

**Comment by dylie** [comment]
> > I think it would be better if we funded "etho.black" as the development team. This way only 1 payment has to be made to their wallet and etho.black devs can use it how they want.
> 
> Ive made some changes to the ECP

Looking good, I agree.

**Comment by Primate411** [comment]
We need to fund the etho.black dev team ASAP so that @fallengravity can give us his full potential as opposed to having to work on other gigs to make up the difference. That's not all, the dev funds will be used by everyone on the team, including @dylie and @Dev-JamesR 

I vote yes on this proposal and I urge all council members to review and give their feedback sooner rather than later.

**Comment by dylie** [comment]
Hello guys, the council multisig wallet is live and ready for your use over at https://decentralizedhosting.online/ Please follow these steps to add the multisig contract to your dashboard:

NOTE: This requires ethomask/metamask to work. @ETHER-1 COUNCIL please use the address provided in ecp https://github.com/Ether1Project/ECPs/issues/17. "Terms of use" Just click read and accept and continue. -> "Wallets" click ADD http://prntscr.com/r0ynot -> Select "Restore deployed wallet" and click next http://prntscr.com/r0yoy9 Fill in a name, for example "ether-1 council sig wallet" + address **0xBA57dFe21F78F921F53B83fFE1958Bbab50F6b46** and click "OK". 


THAT'S IT CONGRATZ! 

-Dylie

**Comment by qbvbsite** [comment]
Looks good to me

**Comment by Primate411** [comment]
We have to fund the dev hustle, the proportion the monthly fund being requested is not substantial for the time being.  40K out of ~190K for this with another ~40K monthly for operational expenses.  This allows all fundamental work to continue full steam ahead while leaving 110K ETHO in the dev fund each month.  I encourage all council members to vote for this & make it unanimous. 

The ECP stipulates we will be able to reconsider this in 90 days, so the commitment is fairly low and I think the effectiveness will be palpable.  The dev team works tirelessly on this project, let's fund them ASAP and get their spirits up!

**Comment by pistol22cal** [comment]
I agree and have voted. - I also fixed the typo I made should have been 50k not 40k - Also alob wants more talking here. So this is me bowing to his demands I hope he is happy. With love always, your friend and mine, pistolcrypt!

**Comment by pistol22cal** [comment]
6/7 votes is passed by supermajority - this ECP passes and will be closed early

**Comment by Primate411** [comment]
We need to vote to change the rules @pistol22cal because we agreed to not close ECP's early (during the voting window) unless there is a unanimous vote.  This is to allow council members away from their computers for a few days a chance to respond and argue against an ECP they disagree with.

We also just changed the amount asked in this ECP from 40K ETHO to 50K ETHO.  Please upvote my post here if you agree with this.  I don't think prior votes for 40K ETHO should automatically be counted as for the changed amount, even though is it a mistaken number.

**Comment by pistol22cal** [comment]
So because i typo'd and some feel i can't just fix the typo we must redo the ECP --- EVEN THOUGH ---- I being perfectly clear about it .........red tape rules ..... its understandable. Just know I think we should be able to have some flexibility and not all be mindless slaves to bureaucracy and red tape.

**Pull request merged**
